### ISSUE TITLE
Build Failed on Xcode6.4

### ISSUE THREAD

**Issue by mrmign** [liruqi/Telegram-iOS#1]
The Error Info:
clang: error: no such file or directory: '/Users/xxxxx/Library/Developer/Xcode/DerivedData/Telegraph-fllymxvmnashjhdgyurfdthcjpqn/Build/Products/Debug-iphonesimulator/MtProtoKit iOS.framework/MtProtoKit iOS'

How to fix that? 
thx

**Comment by liruqi** [comment]
It's currently not working on simulator. Run on device instead.
